### ISSUE TITLE
fråga om serverarkitektur

### ISSUE THREAD

**Issue by J-Zeitler** [emiax/party-elevator#1]
Jag funderade på hur det är tänkt att servern ska fungera. Är server.js bara till för socket och läggs client på en vanlig apacheserver?

Är tanken att vi ska köra http-requests genom den servern också eller vill vi köra allt genom socket-api:et? I så fall (sistnämnda) så behöver vi väl inte express utan bara en ren NodeJS-server?

**Comment by tistatos** [comment]
Ja, va lite fundersam på det själv när jag skulle testa hur det såg ut just nu.
Trodde att server.js skulle agera websocket och http-server.

**Comment by emiax** [comment]
yes än så länge är servern bara till för websockets. Det kan förstås vara bra att sätta upp en enkel express-server i server.js också. I så fall lär man ju strukturera om lite i mappstrukturen också.

**Comment by J-Zeitler** [comment]
Sweet, då låter jag det vara som det är.

**Comment by emiax** [comment]
Å andra sidan kan det vara bra att separera den statiska http-servern från websocket-servern. Det lär ju vara praktiskt att ha två processer.

**Comment by tistatos** [comment]
Ja, det gör la Egentligen att http-servern har möjlighet att ligga på en extern host?

**Comment by emiax** [comment]
Ja, känns ju dumt att hindra den möjligheten i alla fall!
